### ISSUE TITLE
Please specify EXTENT CRS

### ISSUE THREAD

**Issue by pcav** [Kanahiro/tileget#1]
In the instructions it is unclear whether the EXTENT should be defined in 4326 (as it appears the case from my tests) or in the URL default CRS (mostly 3857).
It would be useful to add this to the README.
Thanks.

**Comment by Kanahiro** [comment]
I'm sorry for late response, it seems good feedback! Thanks.

**Comment by Kanahiro** [comment]
now enoughly documented extent as lat/lon.

```
optional arguments:
  -h, --help            show this help message and exit
  --extent EXTENT EXTENT EXTENT EXTENT
                        min_lon min_lat max_lon max_lat, whitespace delimited
```
