### ISSUE TITLE
How do parallel downloads work ?

### ISSUE THREAD

**Issue by Mysterius** [Kanahiro/tileget#11]
Sorry, not really an issue but I had no other way of asking.

How do parallel download works ? Setting it to 4 or 20 doesn't seem to make tiles download faster (the lines scroll at the same speed in the CLI window).

Setting "interval" to 10 or 0 didn't seem to change much either.

It may be because I'm trying to download an "uneven" tilegrid (with lots of empty spaces) and most of the queries are 404  and maybe it's slowing it down. I'm not sure.

**Comment by Mysterius** [comment]
Can confirm that I get the same number of download requests per second, regardless of the --parallel parameter.
The interval parameter works, though (I was mistaken).

**Comment by Kanahiro** [comment]
I treated a number of `parallel` as how many workers run in ThreadPoolExecutor.
Then, we should notice 2x number of workers doesn't mean 2x faster downloading.

v0.4.0, start to support write to MBTIles and drop `parallel` paramater temporaly.
Please wait and see it would be implemented better way!
