### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by wata909** [Kanahiro/tileget#12]
pipでインストールをしようとすると、`FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'`とエラーが出てしまいました。
ご確認頂けますか？

**Comment by Kanahiro** [comment]
@wata909 ご報告ありがとうございます。
ビルドスクリプトをsetup.pyからpyproject.tomlへ移行しました。大丈夫な気がしてます。
もし問題が再現するようでしたら、実行環境やバージョンなどを明記してもらえますか？

**Comment by wata909** [comment]
うまく行きました！
以下，参考情報です。

OS: Windows11 Pro 22H2
Python環境
conda create -n tileget python=3.10 で作成
インストールは完了。`tileget` コマンドで以下のメッセージが表示されるのは確認
```
usage: tileget [-h] [--extent EXTENT EXTENT EXTENT EXTENT] [--geojson GEOJSON] [--minzoom MINZOOM] [--maxzoom MAXZOOM]
               [--interval INTERVAL] [--overwrite] [--timeout TIMEOUT] [--parallel PARALLEL] [--tms]
               tileurl output_dir
tileget: error: the following arguments are required: tileurl, output_dir
```

とりあえず、インストールエラーの報告だったので，いったんクローズします！
