### ISSUE TITLE
Error for output_dir

### ISSUE THREAD

**Issue by pcav** [Kanahiro/tileget#2]
The command

`tileget https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z} ./sample1 --extent 4255991.4309 4358391.4309 2049164.2103 2151564.2103 --minzoom 10 --maxzoom 10`

(also with 4326 extent) returns:

`tileget: error: the following arguments are required: output_dir`

**Comment by Kanahiro** [comment]
URL may need to be quoted, like `"https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}"` and "extent" must be lon-lat value, like `--extent 140.0 35.0 142.0 38.0`.

In my opinion, it is better that unquoted URL also be available.
