### ISSUE TITLE
Support for TMS format ?

### ISSUE THREAD

**Issue by Mysterius** [Kanahiro/tileget#8]
Hello,

Would it be possible to add support for the TMS format ?
It's the same as XYZ, but with a negative Y.

More info here : https://gist.github.com/tmcw/4954720

**Comment by Kanahiro** [comment]
Hello, @Mysterius , Sounds good. I'll support TMS in future version.

**Comment by Mysterius** [comment]
In the meantime, I just edited line 166.
`tiletanic.tileschemes.WebMercator(), geometry, zoom`

to

`tiletanic.tileschemes.WebMercatorBL(), geometry, zoom`

(if anyone needs it in the future)
